#!/usr/bin/env python3
# objects.py - object data for dizzyprice NetHack Price ID tool
# Author: Aubrey Raech (dizzylizzy)
# License: AGPLv3+
# Data is taken from src/objects.c from the NetHack source, which is
#   licensed under the NetHack General Public License
#
# The values of each entry are as follows:
# * "identified name"
# * "description"        potentially randomized
# * probability          relative probability of that object of that type being generated
# * cost                 base cost in zorkmids

amulets = [ ["amulet of ESP",                "circular", 175, 150],
            ["amulet of life saving",       "spherical",  75, 150],
            ["amulet of strangulation",          "oval", 135, 150],
            ["amulet of restful sleep",    "triangular", 135, 150],
            ["amulet versus poison",        "pyramidal", 165, 150],
            ["amulet of change",               "square", 130, 150],
            ["amulet of unchanging",          "concave",  45, 150],
            ["amulet of reflection",        "hexagonal",  75, 150],
            ["amulet of magical breathing", "octagonal",  65, 150] ]

spellbooks = [ ["spellbook of dig",             "parchment",   20, 500],
               ["spellbook of magic missile",   "vellum",      45, 200],
               ["spellbook of fireball",        "ragged",      20, 400],
               ["spellbook of cone of cold",    "dog eared",   10, 400],
               ["spellbook of sleep",           "mottled",     50, 100],
               ["spellbook of finger of death", "stained",      5, 700],
               ["spellbook of light",           "cloth",       45, 100],
               ["spellbook of detect monsters", "leathery",    43, 100],
               ["spellbook of healing",         "white",       40, 100],
               ["spellbook of knock",           "pink",        35, 100],
               ["spellbook of force bolt",      "red",         35, 100],
               ["spellbook of confuse monster", "orange",      30, 200],
               ["spellbook of cure blindness",  "yellow",      25, 200],
               ["spellbook of drain life",      "velvet",      10, 200],
               ["spellbook of slow monster",    "light green", 30, 200],
               ["spellbook of wizard lock",     "dark green",  30, 200],
               ["spellbook of create monster",  "turquoise",   35, 200],
               ["spellbook of detect food",     "cyan",        30, 200],
               ["spellbook of cause fear",      "light blue",  25, 300],
               ["spellbook of clairvoyance",    "dark blue",   15, 300],
               ["spellbook of cure sickness",   "indigo",      32, 300],
               ["spellbook of charm monster",   "magenta",     20, 300],
               ["spellbook of haste self",      "purple",      33, 300],
               ["spellbook of detect unseen",   "violet",      20, 300],
               ["spellbook of levitation",      "tan",         20, 400],
               ["spellbook of extra healing",   "plaid",       27, 300],
               ["spellbook of restore ability", "light brown", 25, 400],
               ["spellbook of invisibility",    "dark brown",  25, 400],
               ["spellbook of detect treasure", "gray",        20, 400],
               ["spellbook of remove curse",    "wrinkled",    25, 300],
               ["spellbook of magic mapping",   "dusty",       18, 500],
               ["spellbook of identify",        "bronze",      20, 300],
               ["spellbook of turn undead",     "copper",      16, 600],
               ["spellbook of polymorph",       "silver",      10, 600],
               ["spellbook of teleport away",   "gold",        15, 600],
               ["spellbook of create familiar", "glittering",  10, 600],
               ["spellbook of cancellation",    "shining",     15, 700],
               ["spellbook of protection",      "dull",        18, 100],
               ["spellbook of jumping",         "thin",        20, 100],
               ["spellbook of stone to flesh",  "thick",       15, 300],
               ["spellbook of blank paper",     "plain",       18, 000] ]

wands = [ ["wand of light",                   "glass", 95, 100],
          ["wand of secret door detection",   "balsa", 50, 150],
          ["wand of enlightenment",         "crystal", 15, 150],
          ["wand of create monster",          "maple", 45, 200],
          ["wand of wishing",                  "pine",  5, 500],
          ["wand of nothing",                   "oak", 25, 100],
          ["wand of striking",                "ebony", 75, 150],
          ["wand of make invisible",         "marble", 45, 150],
          ["wand of slow monster",              "tin", 50, 150],
          ["wand of speed monster",           "brass", 50, 150],
          ["wand of undead turning",         "copper", 50, 150],
          ["wand of polymorph",              "silver", 45, 200],
          ["wand of cancellation",         "platinum", 45, 200],
          ["wand of teleportation",         "iridium", 45, 200],
          ["wand of opening",                  "zinc", 25, 150],
          ["wand of locking",              "aluminum", 25, 150],
          ["wand of probing",               "uranium", 30, 150],
          ["wand of digging",                  "iron", 55, 150],
          ["wand of magic missile",           "steel", 50, 150],
          ["wand of fire",                "hexagonal", 40, 175],
          ["wand of cold",                    "short", 40, 175],
          ["wand of sleep",                   "runed", 50, 175],
          ["wand of death",                    "long",  5, 500],
          ["wand of lightning",              "curved", 40, 175] ]

potions = [ ["potion of gain ability",           "ruby", 42, 300],
            ["potion of restore ability",        "pink", 40, 100],
            ["potion of confusion",            "orange", 42, 100],
            ["potion of blindness",            "yellow", 40, 150],
            ["potion of paralysis",           "emerald", 42, 300],
            ["potion of speed",            "dark green", 42, 200],
            ["potion of levitation",             "cyan", 42, 200],
            ["potion of hallucination",      "sky blue", 40, 100],
            ["potion of invisibility", "brilliant blue", 40, 150],
            ["potion of see invisible",       "magenta", 42,  50],
            ["potion of healing",          "purple-red", 57, 100],
            ["potion of extra healing",          "puce", 47, 100],
            ["potion of gain level",            "milky", 20, 300],
            ["potion of enlightenment",        "swirly", 20, 200],
            ["potion of monster detection",    "bubbly", 40, 150],
            ["potion of object detection",      "smoky", 42, 150],
            ["potion of gain energy",          "cloudy", 42, 150],
            ["potion of sleeping",       "effervescent", 42, 100],
            ["potion of full healing",          "black", 10, 200],
            ["potion of polymorph",            "golden", 10, 200],
            ["potion of booze",                 "brown", 42,  50],
            ["potion of sickness",              "fizzy", 42,  50],
            ["potion of fruit juice",            "dark", 42,  50],
            ["potion of acid",                  "white", 10, 250],
            ["potion of oil",                   "murky", 30, 250],
            ["potion of (un)holy water",        "clear", 92, 100] ]

scrolls = [ ["scroll of enchant armor",              "ZELGO MER",  63,  80],
            ["scroll of destroy armor",         "JUYED AWK YACC",  45, 100],
            ["scroll of confuse monster",                 "NR 9",  53, 100],
            ["scroll of scare monster",   "XIXAXA XOXAXA XUXAXA",  35, 100],
            ["scroll of remove curse",             "PRATYAVAYAH",  65,  80],
            ["scroll of enchant weapon",         "DAIYEN FOOELS",  80,  60],
            ["scroll of create monster",       "LEP GEX VEN ZEA",  45, 200],
            ["scroll of taming",                   "PRIRUTSENIE",  15, 200],
            ["scroll of genocide",                  "ELBIB YLOH",  15, 300],
            ["scroll of light",                 "VERR YED HORRE",  90,  50],
            ["scroll of teleportation",        "VENZAR BORGAVVE",  55, 100],
            ["scroll of gold detection",                 "THARR",  33, 100],
            ["scroll of food detection",               "YUM YUM",  25, 100],
            ["scroll of identify",                  "KERNOD WEL", 180,  20],
            ["scroll of magic mapping",              "ELAM EBOW",  45, 100],
            ["scroll of amnesia",                   "DUAM XNAHT",  35, 200],
            ["scroll of fire",                  "ANDOVA BEGARIN",  30, 100],
            ["scroll of earth",                          "KIRJE",  18, 200],
            ["scroll of punishment",            "VE FORBRYDERNE",  15, 300],
            ["scroll of charging",                "HACKEM MUCHE",  15, 300],
            ["scroll of stinking cloud",             "VELOX NEB",  15, 300],
            ["scroll of blank paper",                "unlabeled",  28,  60] ]

rings = [ ["ring of adornment",                     "wooden", 1, 100],
          ["ring of gain strength",                "granite", 1, 150],
          ["ring of gain constitution",               "opal", 1, 150],
          ["ring of increase accuracy",               "clay", 1, 150],
          ["ring of increase damage",                "coral", 1, 150],
          ["ring of protection",                "black onyx", 1, 100],
          ["ring of regeneration",               "moonstone", 1, 200],
          ["ring of searching",                  "tiger eye", 1, 200],
          ["ring of stealth",                         "jade", 1, 100],
          ["ring of sustain ability",               "bronze", 1, 100],
          ["ring of levitation",                     "agate", 1, 200],
          ["ring of hunger",                         "topaz", 1, 100],
          ["ring of aggravate monster",           "sapphire", 1, 150],
          ["ring of conflict",                        "ruby", 1, 300],
          ["ring of warning",                      "diamond", 1, 100],
          ["ring of poison resistance",              "pearl", 1, 150],
          ["ring of fire resistance",                 "iron", 1, 200],
          ["ring of cold resistance",                "brass", 1, 150],
          ["ring of shock resistance",              "copper", 1, 150],
          ["ring of free action",                  "twisted", 1, 200],
          ["ring of slow digestion",                 "steel", 1, 200],
          ["ring of teleportation",                 "silver", 1, 200],
          ["ring of teleport control",                "gold", 1, 300],
          ["ring of polymorph",                      "ivory", 1, 300],
          ["ring of polymorph control",            "emerald", 1, 300],
          ["ring of invisibility",                    "wire", 1, 150],
          ["ring of see invisible",             "engagement", 1, 150],
          ["ring of protection from shape changers", "shiny", 1, 100] ]


tools = [ ["sack",           "bag", 35,   2],
          ["oilskin sack",   "bag",  5, 100],
          ["bag of holding", "bag", 20, 100],
          ["bag of tricks",  "bag", 20, 100],
          ["tallow candle",   "candle", 20, 10],
          ["wax candle",      "candle",  5, 20],
          ["oil lamp",          "lamp", 45, 10],
          ["magic lamp",        "lamp", 15, 50],
          ["tin whistle",    "whistle",100, 10],
          ["magic whistle",  "whistle", 30, 10],
          ["wooden flute",     "flute",  4, 12],
          ["magic flute",      "flute",  2, 36],
          ["tooled horn",       "horn",  5, 15],
          ["frost horn",        "horn",  2, 50],
          ["fire horn",         "horn",  2, 50],
          ["horn of plenty",    "horn",  2, 50],
          ["wooden harp",       "harp",  4, 50],
          ["magic harp",        "harp",  2, 50],
          ["leather drum",      "drum",  4, 25],
          ["drum of earthquake","drum",  2, 25],
          ["pick-axe", "", 20, 50],
          ["grappling hook", "", 5, 50],
          ["unicorn horn", "", 0, 100] ]


stones = [ ["luckstone",  "gray",  10, 60],
           ["loadstone",  "gray",  10,  1],
           ["touchstone", "gray",   8, 45],
           ["flint",      "gray",  10,  1] ]

weapons = [ ["arrow", "", 55, 2],
            ["elven arrow", "runed arrow", 20, 2],
            ["orcish arrow", "crude arrow", 20, 2],
            ["silver arrow", "", 12, 5],
            ["ya", "bamboo arrow", 15, 4],
            ["crossbow bolt", "", 55, 2],
            ["dart", "", 60,   2],
            ["shuriken", "throwing star", 35,   5],
            ["boomerang", "", 15,  20],
            ["spear", "", 50,   3],
            ["elven spear", "runed spear", 10,   3],
            ["orcish spear", "crude spear", 13,   3],
            ["dwarvish spear", "stout spear", 12,   3],
            ["silver spear", "",  2,  40],
            ["javelin", "throwing spear", 10,   3],
            ["trident", "",  8,   5],
            ["dagger", "", 30,   4],
            ["elven dagger", "runed dagger", 10,   4],
            ["orcish dagger", "crude dagger", 12,   4],
            ["silver dagger", "",  3,  40],
            ["athame", "",  0,   4],
            ["scalpel", "",  0,   6],
            ["knife", "", 20,   4],
            ["stiletto", "",  5,   4],
            ["worm tooth", "",  0,   2],
            ["crysknife", "",  0, 100],
            ["axe", "", 40,   8],
            ["battle-axe", "double-headed axe", 10,  40],
            ["short sword", "",  8,  10],
            ["elven short sword", "runed short sword",  2,  10],
            ["orcish short sword", "crude short sword",  3,  10],
            ["dwarvish short sword", "broad short sword",  2,  10],
            ["scimitar", "curved sword", 15,  15],
            ["silver saber", "",  6,  75],
            ["broadsword", "",  8,  10],
            ["elven broadsword", "runed broadsword",  4,  10],
            ["long sword", "", 50,  15],
            ["two-handed sword", "", 22,  50],
            ["katana", "samurai sword",  4,  80],
            ["tsurugi", "long samurai sword",  0, 500],
            ["runesword", "runed broadsword",  0, 300],
            ["partisan", "vulgar polearm",  5,  10],
            ["ranseur", "hilted polearm",  5,   6],
            ["spetum", "forked polearm",  5,   5],
            ["glaive", "single-edged polearm",  8,   6],
            ["lance", "",  4,  10],
            ["halberd", "angled poleaxe",  8,  10],
            ["bardiche", "long poleaxe",  4,   7],
            ["voulge", "pole cleaver",  4,   5],
            ["dwarvish mattock", "broad pick", 13,  50],
            ["fauchard", "pole sickle",  6,   5],
            ["guisarme", "pruning hook",  6,   5],
            ["bill-guisarme", "hooked polearm",  4,   7],
            ["lucern hammer", "pronged polearm",  5,   7],
            ["bec de corbin", "beaked polearm",  4,   8],
            ["mace", "", 40,   5],
            ["morning star", "", 12,  10],
            ["war hammer", "", 15,   5],
            ["club", "", 12,   3],
            ["rubber hose", "",  0,   3],
            ["quarterstaff", "staff", 11,   5],
            ["aklys", "thonged club",  8,   4],
            ["flail", "", 40,   4],
            ["bullwhip", "",  2,   4],
            ["bow", "", 24, 60],
            ["elven bow", "runed bow", 12, 60],
            ["orcish bow", "crude bow", 12, 60],
            ["yumi", "long bow",  0, 60],
            ["sling", "", 40, 20],
            ["crossbow", "", 45, 40] ]

armor = [ ["elven leather helm", "leather hat",  6,  8],
          ["orcish helm", "iron skull cap",  6, 10],
          ["dwarvish iron helm", "hard hat",  6, 20],
          ["fedora", "",  0,  1],
          ["cornuthaum", "conical hat",  3, 80],
          ["dunce cap", "conical hat",  3,  1],
          ["dented pot", "",  2,  8],
          # HELMET SHUFFLE = plumed etched crested visored
          ["helmet", "plumed etched crested visored helmet", 10, 10],
          ["helm of brilliance", "plumed etched crested visored helmet",  6, 50],
          ["helm of opposite alignment", "plumed etched crested visored helmet",  6, 50],
          ["helm of telepathy", "plumed etched crested visored helmet",  2, 50],

          ["gray dragon scale mail", "",   0, 1200],
          ["silver dragon scale mail", "", 0, 1200],
          ["red dragon scale mail", "",    0,  900],
          ["white dragon scale mail", "",  0,  900],
          ["orange dragon scale mail", "", 0,  900],
          ["black dragon scale mail", "",  0, 1200],
          ["blue dragon scale mail", "",   0,  900],
          ["green dragon scale mail", "",  0,  900],
          ["yellow dragon scale mail", "", 0,  900],
          ["gray dragon scales", "",       0,  700],
          ["silver dragon scales", "",     0,  700],
          ["red dragon scales", "",        0,  500],
          ["white dragon scales", "",      0,  500],
          ["orange dragon scales", "",     0,  500],
          ["black dragon scales", "",      0,  700],
          ["blue dragon scales", "",       0,  500],
          ["green dragon scales", "",      0,  500],
          ["yellow dragon scales", "",     0,  500],

          ["plate mail", "", 44, 600],
          ["crystal plate mail", "", 10, 820],
          ["bronze plate mail", "", 25, 400],
          ["splint mail", "", 62,  80],
          ["banded mail", "", 72,  90],
          ["dwarvish mithril-coat", "", 10, 240],
          ["elven mithril-coat", "", 15, 240],
          ["chain mail", "", 72,  75],
          ["orcish chain mail", "crude chain mail", 20,  75],
          ["scale mail", "", 72,  45],
          ["studded leather armor", "", 72,  15],
          ["ring mail", "", 72, 100],
          ["orcish ring mail", "crude ring mail", 20,  80],
          ["leather armor", "", 82,   5],
          ["leather jacket", "", 12,  10],
          ["Hawaiian shirt", "",  8,   3],
          ["T-shirt", "",  2,   2],

          ["mummy wrapping", "",  0,  2],
          ["elven cloak", "faded pall",  8, 60],
          ["orcish cloak", "coarse mantelet",  8, 40],
          ["dwarvish cloak", "hooded cloak",  8, 50],
          ["oilskin cloak", "slippery cloak",  8, 50],
          ["robe", "",  3, 50],
          ["alchemy smock", "apron",  9, 50],
          ["leather cloak", "",  8, 40],
          # CLOAK SHUFFLES = 'tattered cape', 'opera cloak', 'ornamental cope', 'piece of cloth'
          ["cloak of protection", "tattered cape opera cloak ornamental cope piece of cloth",  9, 50],
          ["cloak of invisibility", "tattered cape opera cloak ornamental cope piece of cloth", 10, 60],
          ["cloak of magic resistance", "tattered cape opera cloak ornamental cope piece of cloth",  2, 60],
          ["cloak of displacement", "tattered cape opera cloak ornamental cope piece of cloth", 10, 50],

          ["small shield", "", 6,  3],
          ["elven shield", "blue and green shield", 2,  7],
          ["Uruk-hai shield", "white-handed shield", 2,  7],
          ["orcish shield", "red-eyed shield", 2,  7],
          ["large shield", "", 7, 10],
          ["dwarvish roundshield", "large round shield", 4, 10],
          ["shield of reflection", "polished silver shield", 3, 50],

          # SHUFFLED GLOVES = old padded riding fencing
          ["leather gloves", "old padded riding fencing gloves", 16,  8],
          ["gauntlets of fumbling", "old padded riding fencing gloves",  8, 50],
          ["gauntlets of power", "old padded riding fencing gloves",  8, 50],
          ["gauntlets of dexterity", "old padded riding fencing gloves",  8, 50],

          ["low boots", "walking shoes", 25,  8],
          ["iron shoes", "hard shoes",  7, 16],
          ["high boots", "jackboots", 15, 12],
          # SHUFFLED BOOTS = combat jungle hiking mud buckled riding snow
          ["speed boots", "combat jungle hiking mud buckled riding snow boots", 12, 50],
          ["water walking boots", "combat jungle hiking mud buckled riding snow boots", 12, 50],
          ["jumping boots", "combat jungle hiking mud buckled riding snow boots", 12, 50],
          ["elven boots", "combat jungle hiking mud buckled riding snow boots", 12,  8],
          ["kicking boots", "combat jungle hiking mud buckled riding snow boots", 12,  8],
          ["fumble boots", "combat jungle hiking mud buckled riding snow boots", 12, 30],
          ["levitation boots", "combat jungle hiking mud buckled riding snow boots", 12, 30] ]
